-- Statements! 
-- Abstraction and State 
-- is the push to abstraction, in part fueled by, a desire to reduce the cognative load incurred by keeping track of state and it's resultant effects.   
-- State is the source of uncertainty, and lack of control in programming. Quest to Control randomness in pogramming. 
-- Spell casting is programming with a high degree of randomness. For some programmers, it is untenable, for others they crave the opertunity to juggle more of it. 
--  
