-- burn notes 
-- create a folder with the date-name-ext format 
-- having shut down the image-appliance  
-- From inside Virtual Box we will export the image into a .ova file 
-- pushing it up on line is less efficient than burning to disk. 
-- compress the .ova file to zip 
-- burn the zip file. 
--
