module SnpUntu where 
-- trying snap because yesod nice as it is wont load into the 512mb 12.04 
-- rewinding  the yesogsothoth image back to ghc-7.6.3 and the haskell platform. 
-- yesogsothoth has been renamed to SnapUntu as we explore the Snap Web framework 
-- [42 of 85] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o )
-- Failed to install lens-4.1.2
-- cabal: Error: some packages failed to install:
-- lens-4.1.2 failed during the building phase. The exception was:
-- ExitFailure 9
-- snap-0.13.2.4 depends on lens-4.1.2 which failed to install. 
-- caball install lens-4.1.2 -- try broke on step [42] 
-- cabal install lens 
-- [42 of 85] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o )
-- [43 of 85] Compiling Control.Lens.Internal.Deque ( src/Control/Lens/Internal/Deque.hs, dist/build/Control/Lens/Internal/Deque.o )
-- Failed to install lens-4.1.2
-- cabal: Error: some packages failed to install:
-- lens-4.1.2 failed during the building phase. The exception was:
-- ExitFailure 9 
-- trying cabal install lens again 
-- [42 of 85] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o )
-- Failed to install lens-4.1.2
-- cabal: Error: some packages failed to install:
-- lens-4.1.2 failed during the building phase. The exception was:
-- ExitFailure 9 
-- tying snap install again 
-- [42 of 85] Compiling Control.Lens.Cons ( src/Control/Lens/Cons.hs, dist/build/Control/Lens/Cons.o )
-- Failed to install lens-4.1.2 
-- WTF nothing installs simply !!! 
------------------------------------------
-- Trying for Scotty 
-- rewinding SnapUntu back to pre-install and will rename scottyUntu 

-- reset to HaskUntuPlatformed 
-- attempted to update cabal to 18 from 16 
-- [29 of 72] Compiling Distribution.Simple.Command ( Distribution/Simple/Command.hs, dist/build/Distribution/Simple/Command.o )
-- Failed to install Cabal-1.18.1.3
-- cabal: Error: some packages failed to install:
-- Cabal-1.18.1.3 failed during the building phase. The exception was:
-- ExitFailure 9
-- cabal-install-1.18.0.3 depends on Cabal-1.18.1.3 which failed to install.
---------------------------------------------------
---------SCOTTY-ROCKS-!!!--------------------------
---------------------------------------------------
-- In-place registering scotty-0.7.1...
-- Installing library in /root/.cabal/lib/scotty-0.7.1/ghc-7.6.3
-- Registering scotty-0.7.1...
-- Installed scotty-0.7.1 
---------------------------------------------------

