module mar4 where 

{- 
 - 
 -
 - diapers.com
 - 545 mil 
 - Bikini.com 
 - 
 - walker-digital 
 - 
 - CPA - Tech noob. 
 -
 - Accelerator /= incubator
 -  Accelerator /= invester network 
 -  Accelerator  
 - Tom 
 - 29th street 
 - 	early stage 
 - 	6 sessions 60 companies in play 
 - 		6/11 still in contact 
 - 	free legal 
 - 	PayPal 
 -  
 - Fund raising teaching at GA 
 - 		capital isn't always the most 
 - 		other issue can predominate 
 - 		"product-Market fit" 
 - 		"is the cost equity worth the money"	
 -		y-combinator 
 -	4 years ago there were none 
 -		now many 
 -
 -	Grads advising 
 -		
 -	Rapid product progress 
 -		mentors 
 -			dig market 
 -			channel sales 
 -		best approach 
 -
 -	prerevenue preproduct 
 -		team matters most 
 -
 -	
 -	prototype
 -
 - 	speed of decisions 
 - 		with little or no data 
 - 			30 min not 6 weeks 
 -
 - 	Passion 
 - 		suspension of disbelief 
 - 			delusional? 
 - 		with some reflection 
 - 		Authenticity 
 - 			they come from direct experience 
 - 		execution 
 - 			quick turn around 
 - 			quick iteration 
 -		overlapping skills 
 -			complimenting skills 
 -		getting things done 
 -		red flag 
 -			no tech or no biz
 -		Sales skill is necessary with tech 
 -		
 -		pivots 
 -			and 
 -		
 -		Judging people 
 -			harder than the idea 
 -		Idea good then good team 
 -
 - 	disruptive 
 - 		I invest in things I know nothing about? 
 -
 - 		team and market size and idea 
 - 			is this co a good match for mentors 
 - 				and NYC 
 -					is there an advantage for being here
 -		foursaquare in Mountain View ? 
 - 	disruptive 
 -		crypto currencey
 -		big data with insights 
 -		body streaming data 
 -		education 
 -		Health Insurance 
 -		
 -	things that have come and might be going 
 -		edu 
 -		market places 
 -		personal services app. 
 -		
 -	Accelerator 
 -	
 -	
 -	failure 
 -	know when you are not succeeding 
 -		pivot or perioette 
 -	
 -	a hidden team problems
 -		sex between partners cools off 
 -
 - companies outlive the marrage 
 - 		
 - Exits 
 - 		unpredicable 
 -		failures 
 -		decent burial 
 -
 -	Hold time is 6 - 8 years avg
 -		funds return over ten years 
 -		J curve 
 -			losses early 
 -				before market effects 	
 -	Entered in 2007 
 -		some are now exiting 
 -	
 -	Knowing when to Pivot 
 -		
 -	? Long tails ? or are their only short tails 
 -		 
 -	
 -	Pitching 
 -		perseverence but pivotable 
 -  
 -  QR code creater 
 -  	for bus stops 
 -  		they had to pivot 
 -  three days brainstorm 
 -  	next biz 
 -  		two years later 
 -  Team was what mattered 
 -  	
 -  endless TV 
 -  	swipe for story 
 -  	scroll for channel 
 -
 -  When idea is further along 
 -  	less pivots 
 -  		but tighter arc
 -  pie-charts 
 -  	good space too much opertunity 
 -  		but challenge is focus 
 -  
 - 	Returning companies 
 - 		apply again 
 - 			2nd try 
 - 				was keeper 
 - 	90% -- wont get dime in funding 
 - 	90% of those that get funding will fail 
 - 	1% success rate?   
 - 	
 - 	not willing to comeback over and over get a W-2 job
 - 		get better with each attempt
 -			need to show that they are improving 
 -
 -	3000 a year ask 
 -		I am not the customer for your 
 -	entertain -- look nice -- 
 -	impr -- you or your tranction is impressive 
 -	info -- what is it you do 
 -			no resume words 
 -		cosmetic improvements not enough 
 -
 - fund raising is about rejection 
 -		50 no s for foursquare 
 -
 - internet of things 
 - 		tech starter accelorator 
 - 
 - 13 questions application 
 - 
 - a one pager 
 - 		paragraph in the email 
 - 			a warm intro through someone I know 
 -  	the right brevity 
 -  		not an application 
 -  
 -  Outsourced my tech 
 -  	no CTO ? 
 -  		best if you have one 
 -  			find one 
 -  Dating analogies 
 -  	and job interview analogies 
 -
 - people coming in 
 - Weaker or stronger 
 - 		in ... ? 
 - 
 - CoFounders Lab
 - Founder Dating 
 - Angel List 
 - Even Craigslist 
 - Or meetings like this 
 - 		`
 - Trick someone into thinking that you have a great idea 
 - 			convinse people to work for free .
 -				internship?? 
 -			founding team needs the core team to have those skills 
 -				Interns to find but can't depend 
 -					a senior person 
 -	
 -	How little research they have done before coming to me
 -		3/4 or applicants have no idea what I've done already 
 - 
 - 	Losers can do everything right and the market still said NO
 -
 - 	Who is down stream and who is upstreams 
 -
 - 	crypto-currency 
 -
 - seed-VC is much further along than the accelerator 
 -
 - Companies that are already there are most likely to get traction overtime, 
 -
 - Convertable notes -- some 
 - 		25 - 250 
 - 		funds era 
 - 		
 - 	Brokers 8% approaching you 
 - 		run away
 -
 -
 -
 -
 - 			
 -	
 -
 -
 -		
